name:  CI/CD
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      -  master

  pull_request:
    branches:
      - master

jobs:
  primary:
    runs-on: ubuntu-latest     

      # should save this keys in github, settings of the project, secrets :
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
      - name: aws deploy
        run: BUILD_DIRECTORY=build BUCKET_NAME=demo-test.in AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws